version: '3.7'

services:
  postgres: 
    image: postgres:latest
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
      POSTGRES_DB: demo
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      

